### PR TITLE
Run tests against all Saucelabs browsers! :-D

### PR DESCRIPTION
**Pull request by JakeChampion**
Zuul is the simplest way to add SauceLabs.

This needs some env vars set on CI:
```bash
SAUCE_USERNAME=
SAUCE_ACCESS_KEY=
```

This is the step required to make it work in travis - https://github.com/defunctzombie/zuul/wiki/Travis-ci#5-final-step

<details><summary>*Results from zuul:*</summary>
```bash
/Code/oss/proclaim sauce*
❯ ./node_modules/.bin/zuul -ui mocha-bdd -- test/unit/lib/proclaim.js
- testing: iphone @ Mac 10.9: 7.0
- testing: iphone @ Mac 10.10: 7.1 8.1 8.2 8.3 8.4 9.0 9.1 9.2
- testing: iphone @ Mac 10.11: 9.3
- testing: ipad @ Mac 10.9: 7.0
- testing: ipad @ Mac 10.10: 7.1 8.1 8.2 8.3 8.4 9.0 9.1 9.2
- testing: ipad @ Mac 10.11: 9.3
- testing: firefox @ Mac 10.9: 4 6 20
- testing: firefox @ Windows 2003: 5 10 18 22 23 29 30 31 36
- testing: firefox @ Mac 10.11: 7 13 26 33 34 43
- testing: firefox @ Windows 2012 R2: 8 19 27 38 44
- testing: firefox @ Mac 10.8: 9 12 14 47
- testing: firefox @ Windows 2008: 11 24 37
- testing: firefox @ Linux: 15
- testing: firefox @ Windows 10: 16 21 32 35 41 42
- testing: firefox @ Windows 2012: 17 25 28 39 45
- testing: firefox @ Mac 10.10: 40 46
- testing: safari @ Windows 2008: 5
- testing: safari @ Mac 10.8: 6
- testing: safari @ Mac 10.9: 7
- testing: safari @ Mac 10.10: 8
- testing: safari @ Mac 10.11: 9
- testing: chrome @ Windows 2012: 26 27 29 41 48 52
- testing: chrome @ Windows 10: 28 32
- testing: chrome @ Windows 2012 R2: 30 37 38
- testing: chrome @ Mac 10.11: 31 34 35 36 39 44 49 51
- testing: chrome @ Windows 2003: 33
- testing: chrome @ Mac 10.8: 40 42
- testing: chrome @ Windows 2008: 43 45 47
- testing: chrome @ Mac 10.9: 46
- testing: chrome @ Mac 10.10: 50
- testing: internet explorer @ Windows 2003: 6 7 8
- testing: internet explorer @ Windows 2008: 9
- testing: internet explorer @ Windows 2012: 10
- testing: internet explorer @ Windows 10: 11
- testing: microsoftedge @ Windows 10: 13
- testing: opera @ Windows 2003: 11 12
- testing: android @ Linux: 4.0 4.1 4.2 4.3 4.4 5.0 5.1
- queuing: <iphone 8.1 on Mac 10.10>
- queuing: <iphone 8.3 on Mac 10.10>
- queuing: <iphone 7.0 on Mac 10.9>
- queuing: <iphone 8.2 on Mac 10.10>
- queuing: <iphone 7.1 on Mac 10.10>
- starting: <iphone 8.3 on Mac 10.10>
- starting: <iphone 8.1 on Mac 10.10>
- passed: <iphone 8.3 on Mac 10.10>
- queuing: <iphone 8.4 on Mac 10.10>
- passed: <iphone 8.1 on Mac 10.10>
- queuing: <iphone 9.0 on Mac 10.10>
- starting: <iphone 8.2 on Mac 10.10>
- starting: <iphone 7.0 on Mac 10.9>
- passed: <iphone 8.2 on Mac 10.10>
- queuing: <iphone 9.1 on Mac 10.10>
- passed: <iphone 7.0 on Mac 10.9>
- queuing: <iphone 9.2 on Mac 10.10>
- starting: <iphone 7.1 on Mac 10.10>
- starting: <iphone 8.4 on Mac 10.10>
- passed: <iphone 7.1 on Mac 10.10>
- queuing: <iphone 9.3 on Mac 10.11>
- passed: <iphone 8.4 on Mac 10.10>
- queuing: <ipad 7.0 on Mac 10.9>
- starting: <iphone 9.1 on Mac 10.10>
- starting: <iphone 9.2 on Mac 10.10>
- passed: <iphone 9.1 on Mac 10.10>
- queuing: <ipad 7.1 on Mac 10.10>
- starting: <iphone 9.0 on Mac 10.10>
- passed: <iphone 9.2 on Mac 10.10>
- queuing: <ipad 8.1 on Mac 10.10>
- passed: <iphone 9.0 on Mac 10.10>
- queuing: <ipad 8.2 on Mac 10.10>
- starting: <ipad 7.0 on Mac 10.9>
- passed: <ipad 7.0 on Mac 10.9>
- queuing: <ipad 8.3 on Mac 10.10>
- starting: <ipad 7.1 on Mac 10.10>
- starting: <ipad 8.1 on Mac 10.10>
- passed: <ipad 7.1 on Mac 10.10>
- queuing: <ipad 8.4 on Mac 10.10>
- passed: <ipad 8.1 on Mac 10.10>
- queuing: <ipad 9.0 on Mac 10.10>
- starting: <ipad 8.2 on Mac 10.10>
- starting: <ipad 8.3 on Mac 10.10>
- passed: <ipad 8.2 on Mac 10.10>
- queuing: <ipad 9.1 on Mac 10.10>
- passed: <ipad 8.3 on Mac 10.10>
- queuing: <ipad 9.2 on Mac 10.10>
- starting: <iphone 9.3 on Mac 10.11>
- starting: <ipad 8.4 on Mac 10.10>
- passed: <iphone 9.3 on Mac 10.11>
- queuing: <ipad 9.3 on Mac 10.11>
- starting: <ipad 9.1 on Mac 10.10>
- passed: <ipad 9.1 on Mac 10.10>
- passed: <ipad 8.4 on Mac 10.10>
- queuing: <firefox 5 on Windows 2003>
- starting: <ipad 9.0 on Mac 10.10>
- starting: <firefox 5 on Windows 2003>
- queuing: <firefox 4 on Mac 10.9>
- passed: <ipad 9.0 on Mac 10.10>
- queuing: <firefox 6 on Mac 10.9>
- passed: <firefox 5 on Windows 2003>
- queuing: <firefox 7 on Mac 10.11>
- starting: <ipad 9.2 on Mac 10.10>
- passed: <ipad 9.2 on Mac 10.10>
- queuing: <firefox 8 on Windows 2012 R2>
- starting: <firefox 6 on Mac 10.9>
- starting: <firefox 4 on Mac 10.9>
- starting: <firefox 8 on Windows 2012 R2>
- passed: <firefox 6 on Mac 10.9>
- queuing: <firefox 9 on Mac 10.8>
- starting: <firefox 7 on Mac 10.11>
- passed: <firefox 4 on Mac 10.9>
- queuing: <firefox 10 on Windows 2003>
- passed: <firefox 8 on Windows 2012 R2>
- queuing: <firefox 11 on Windows 2008>
- passed: <firefox 7 on Mac 10.11>
- queuing: <firefox 12 on Mac 10.8>
- starting: <firefox 10 on Windows 2003>
- starting: <firefox 9 on Mac 10.8>
- starting: <firefox 11 on Windows 2008>
- passed: <firefox 10 on Windows 2003>
- queuing: <firefox 13 on Mac 10.11>
- passed: <firefox 9 on Mac 10.8>
- queuing: <firefox 14 on Mac 10.8>
- passed: <firefox 11 on Windows 2008>
- starting: <firefox 12 on Mac 10.8>
- queuing: <firefox 15 on Linux>
- starting: <firefox 15 on Linux>
- starting: <firefox 14 on Mac 10.8>
- passed: <firefox 15 on Linux>
- starting: <firefox 13 on Mac 10.11>
- queuing: <firefox 16 on Windows 10>
- starting: <firefox 16 on Windows 10>
- passed: <firefox 14 on Mac 10.8>
- queuing: <firefox 17 on Windows 2012>
- waiting: <firefox 12 on Mac 10.8>
- starting: <firefox 17 on Windows 2012>
- passed: <firefox 16 on Windows 10>
- queuing: <firefox 18 on Windows 2003>
- waiting: <firefox 13 on Mac 10.11>
- starting: <ipad 9.3 on Mac 10.11>
- starting: <firefox 18 on Windows 2003>
- passed: <firefox 17 on Windows 2012>
- queuing: <firefox 19 on Windows 2012 R2>
- starting: <firefox 19 on Windows 2012 R2>
- waiting: <firefox 12 on Mac 10.8>
- passed: <firefox 18 on Windows 2003>
- queuing: <firefox 20 on Mac 10.9>
- passed: <ipad 9.3 on Mac 10.11>
- passed: <firefox 19 on Windows 2012 R2>
- queuing: <firefox 21 on Windows 10>
- queuing: <firefox 22 on Windows 2003>
- starting: <firefox 21 on Windows 10>
- starting: <firefox 22 on Windows 2003>
- waiting: <firefox 13 on Mac 10.11>
- starting: <firefox 20 on Mac 10.9>
- passed: <firefox 22 on Windows 2003>
- waiting: <firefox 12 on Mac 10.8>
- queuing: <firefox 23 on Windows 2003>
- passed: <firefox 21 on Windows 10>
- queuing: <firefox 24 on Windows 2008>
- starting: <firefox 23 on Windows 2003>
- passed: <firefox 20 on Mac 10.9>
- queuing: <firefox 25 on Windows 2012>
- starting: <firefox 24 on Windows 2008>
- waiting: <firefox 13 on Mac 10.11>
- passed: <firefox 24 on Windows 2008>
- starting: <firefox 25 on Windows 2012>
- queuing: <firefox 26 on Mac 10.11>
- passed: <firefox 23 on Windows 2003>
- queuing: <firefox 27 on Windows 2012 R2>
- passed: <firefox 25 on Windows 2012>
- starting: <firefox 26 on Mac 10.11>
- queuing: <firefox 28 on Windows 2012>
- starting: <firefox 27 on Windows 2012 R2>
- waiting: <firefox 12 on Mac 10.8>
- restarting: <firefox 12 on Mac 10.8>
- starting: <firefox 28 on Windows 2012>
- passed: <firefox 26 on Mac 10.11>
- queuing: <firefox 29 on Windows 2003>
- passed: <firefox 27 on Windows 2012 R2>
- queuing: <firefox 30 on Windows 2003>
- passed: <firefox 28 on Windows 2012>
- queuing: <firefox 31 on Windows 2003>
- starting: <firefox 29 on Windows 2003>
- waiting: <firefox 13 on Mac 10.11>
- restarting: <firefox 13 on Mac 10.11>
- starting: <firefox 12 on Mac 10.8>
- starting: <firefox 30 on Windows 2003>
- starting: <firefox 31 on Windows 2003>
- passed: <firefox 29 on Windows 2003>
- queuing: <firefox 32 on Windows 10>
- passed: <firefox 12 on Mac 10.8>
- queuing: <firefox 33 on Mac 10.11>
- passed: <firefox 30 on Windows 2003>
- queuing: <firefox 34 on Mac 10.11>
- starting: <firefox 32 on Windows 10>
- passed: <firefox 31 on Windows 2003>
- queuing: <firefox 35 on Windows 10>
- starting: <firefox 34 on Mac 10.11>
- starting: <firefox 33 on Mac 10.11>
- starting: <firefox 35 on Windows 10>
- starting: <firefox 13 on Mac 10.11>
- passed: <firefox 32 on Windows 10>
- queuing: <firefox 36 on Windows 2003>
- passed: <firefox 13 on Mac 10.11>
- queuing: <firefox 37 on Windows 2008>
- starting: <firefox 36 on Windows 2003>
- passed: <firefox 34 on Mac 10.11>
- queuing: <firefox 38 on Windows 2012 R2>
- passed: <firefox 33 on Mac 10.11>
- passed: <firefox 35 on Windows 10>
- queuing: <firefox 39 on Windows 2012>
- starting: <firefox 37 on Windows 2008>
- queuing: <firefox 40 on Mac 10.10>
- passed: <firefox 36 on Windows 2003>
- queuing: <firefox 41 on Windows 10>
- starting: <firefox 38 on Windows 2012 R2>
- starting: <firefox 39 on Windows 2012>
- starting: <firefox 40 on Mac 10.10>
- passed: <firefox 37 on Windows 2008>
- queuing: <firefox 42 on Windows 10>
- starting: <firefox 41 on Windows 10>
- passed: <firefox 39 on Windows 2012>
- queuing: <firefox 43 on Mac 10.11>
- passed: <firefox 38 on Windows 2012 R2>
- queuing: <firefox 44 on Windows 2012 R2>
- starting: <firefox 42 on Windows 10>
- passed: <firefox 41 on Windows 10>
- starting: <firefox 44 on Windows 2012 R2>
- queuing: <firefox 45 on Windows 2012>
- passed: <firefox 40 on Mac 10.10>
- queuing: <firefox 46 on Mac 10.10>
- passed: <firefox 42 on Windows 10>
- queuing: <firefox 47 on Mac 10.8>
- passed: <firefox 44 on Windows 2012 R2>
- queuing: <safari 5 on Windows 2008>
- starting: <firefox 45 on Windows 2012>
- starting: <firefox 43 on Mac 10.11>
- starting: <firefox 46 on Mac 10.10>
- starting: <safari 5 on Windows 2008>
- starting: <firefox 47 on Mac 10.8>
- passed: <firefox 45 on Windows 2012>
- queuing: <safari 6 on Mac 10.8>
- passed: <firefox 43 on Mac 10.11>
- queuing: <safari 7 on Mac 10.9>
- passed: <safari 5 on Windows 2008>
- queuing: <safari 8 on Mac 10.10>
- starting: <safari 6 on Mac 10.8>
- passed: <firefox 46 on Mac 10.10>
- queuing: <safari 9 on Mac 10.11>
- passed: <firefox 47 on Mac 10.8>
- queuing: <chrome 26 on Windows 2012>
- starting: <safari 7 on Mac 10.9>
- starting: <chrome 26 on Windows 2012>
- starting: <safari 8 on Mac 10.10>
- passed: <safari 6 on Mac 10.8>
- queuing: <chrome 27 on Windows 2012>
- starting: <chrome 27 on Windows 2012>
- passed: <chrome 26 on Windows 2012>
- queuing: <chrome 28 on Windows 10>
- starting: <safari 9 on Mac 10.11>
- passed: <safari 7 on Mac 10.9>
- queuing: <chrome 29 on Windows 2012>
- passed: <chrome 27 on Windows 2012>
- queuing: <chrome 30 on Windows 2012 R2>
- starting: <chrome 28 on Windows 10>
- passed: <safari 8 on Mac 10.10>
- queuing: <chrome 31 on Mac 10.11>
- starting: <chrome 30 on Windows 2012 R2>
- starting: <chrome 29 on Windows 2012>
- passed: <chrome 28 on Windows 10>
- queuing: <chrome 32 on Windows 10>
- passed: <chrome 30 on Windows 2012 R2>
- passed: <safari 9 on Mac 10.11>
- queuing: <chrome 33 on Windows 2003>
- starting: <chrome 32 on Windows 10>
- queuing: <chrome 34 on Mac 10.11>
- starting: <chrome 33 on Windows 2003>
- passed: <chrome 29 on Windows 2012>
- queuing: <chrome 35 on Mac 10.11>
- starting: <chrome 31 on Mac 10.11>
- passed: <chrome 32 on Windows 10>
- queuing: <chrome 36 on Mac 10.11>
- passed: <chrome 33 on Windows 2003>
- queuing: <chrome 37 on Windows 2012 R2>
- starting: <chrome 35 on Mac 10.11>
- starting: <chrome 34 on Mac 10.11>
- starting: <chrome 37 on Windows 2012 R2>
- passed: <chrome 31 on Mac 10.11>
- queuing: <chrome 38 on Windows 2012 R2>
- starting: <chrome 38 on Windows 2012 R2>
- passed: <chrome 35 on Mac 10.11>
- queuing: <chrome 39 on Mac 10.11>
- passed: <chrome 34 on Mac 10.11>
- queuing: <chrome 40 on Mac 10.8>
- passed: <chrome 37 on Windows 2012 R2>
- queuing: <chrome 41 on Windows 2012>
- starting: <chrome 36 on Mac 10.11>
- starting: <chrome 41 on Windows 2012>
- starting: <chrome 40 on Mac 10.8>
- passed: <chrome 38 on Windows 2012 R2>
- queuing: <chrome 42 on Mac 10.8>
- starting: <chrome 42 on Mac 10.8>
- passed: <chrome 36 on Mac 10.11>
- queuing: <chrome 43 on Windows 2008>
- passed: <chrome 41 on Windows 2012>
- queuing: <chrome 44 on Mac 10.11>
- starting: <chrome 43 on Windows 2008>
- passed: <chrome 40 on Mac 10.8>
- starting: <chrome 39 on Mac 10.11>
- queuing: <chrome 45 on Windows 2008>
- passed: <chrome 42 on Mac 10.8>
- queuing: <chrome 46 on Mac 10.9>
- starting: <chrome 45 on Windows 2008>
- passed: <chrome 43 on Windows 2008>
- queuing: <chrome 47 on Windows 2008>
- passed: <chrome 39 on Mac 10.11>
- queuing: <chrome 48 on Windows 2012>
- starting: <chrome 46 on Mac 10.9>
- starting: <chrome 47 on Windows 2008>
- starting: <chrome 48 on Windows 2012>
- passed: <chrome 45 on Windows 2008>
- queuing: <chrome 49 on Mac 10.11>
- passed: <chrome 47 on Windows 2008>
- queuing: <chrome 50 on Mac 10.10>
- starting: <chrome 44 on Mac 10.11>
- passed: <chrome 48 on Windows 2012>
- passed: <chrome 46 on Mac 10.9>
- queuing: <chrome 52 on Windows 2012>
- queuing: <chrome 51 on Mac 10.11>
- starting: <chrome 49 on Mac 10.11>
- starting: <chrome 50 on Mac 10.10>
- passed: <chrome 44 on Mac 10.11>
- queuing: <internet explorer 6 on Windows 2003>
- starting: <chrome 52 on Windows 2012>
- starting: <internet explorer 6 on Windows 2003>
- starting: <chrome 51 on Mac 10.11>
- passed: <chrome 49 on Mac 10.11>
- passed: <chrome 52 on Windows 2012>
- queuing: <internet explorer 8 on Windows 2003>
- queuing: <internet explorer 7 on Windows 2003>
- passed: <chrome 50 on Mac 10.10>
- queuing: <internet explorer 9 on Windows 2008>
- starting: <internet explorer 8 on Windows 2003>
- starting: <internet explorer 7 on Windows 2003>
- passed: <internet explorer 6 on Windows 2003>
- passed: <chrome 51 on Mac 10.11>
- queuing: <internet explorer 10 on Windows 2012>
- queuing: <internet explorer 11 on Windows 10>
- starting: <internet explorer 9 on Windows 2008>
- starting: <internet explorer 11 on Windows 10>
- starting: <internet explorer 10 on Windows 2012>
- passed: <internet explorer 8 on Windows 2003>
- queuing: <microsoftedge 13 on Windows 10>
- passed: <internet explorer 9 on Windows 2008>
- passed: <internet explorer 7 on Windows 2003>
- queuing: <opera 11 on Windows 2003>
- queuing: <opera 12 on Windows 2003>
- passed: <internet explorer 11 on Windows 10>
- queuing: <android 4.0 on Linux>
- passed: <internet explorer 10 on Windows 2012>
- starting: <microsoftedge 13 on Windows 10>
- queuing: <android 4.1 on Linux>
- starting: <opera 11 on Windows 2003>
- starting: <opera 12 on Windows 2003>
- passed: <microsoftedge 13 on Windows 10>
- queuing: <android 4.2 on Linux>
- passed: <opera 11 on Windows 2003>
- queuing: <android 4.3 on Linux>
- passed: <opera 12 on Windows 2003>
- queuing: <android 4.4 on Linux>
- starting: <android 4.0 on Linux>
- starting: <android 4.3 on Linux>
- starting: <android 4.1 on Linux>
- passed: <android 4.0 on Linux>
- queuing: <android 5.0 on Linux>
- starting: <android 4.2 on Linux>
- passed: <android 4.1 on Linux>
- queuing: <android 5.1 on Linux>
- passed: <android 4.3 on Linux>
- passed: <android 4.2 on Linux>
- starting: <android 4.4 on Linux>
- passed: <android 4.4 on Linux>
- starting: <android 5.0 on Linux>
- starting: <android 5.1 on Linux>
- passed: <android 5.0 on Linux>
- passed: <android 5.1 on Linux>
all browsers passed
~/Code/oss/proclaim sauce 15m 53s
```
</details>

### CODE REVIEW

**Comment by JakeChampion** [comment]
This needs some env vars set on CI:
```bash
SAUCE_USERNAME=
SAUCE_ACCESS_KEY=
```

**Comment by JakeChampion** [comment]
```bash
Tested http://127.0.0.1:9999/test/browser/test.html
Platform: Mac 10.9,chrome,47
Passed: false
Url https://saucelabs.com/jobs/6eca8aec947c477fa561b3b1144730d2

Tested http://127.0.0.1:9999/test/browser/test.html
Platform: Windows 2003,opera,12
Passed: false
Url https://saucelabs.com/jobs/c2dc1451e3fb49949a78bc729d7c4bdd

 114 / 116 browsers passed tests
```

**Comment by rowanmanning** [comment]
@JakeChampion this is awesome! OK for me to recreate this branch on origin and add environment vars?

**Comment by JakeChampion** [comment]
Of course :-)

**Comment by rowanmanning** [comment]
Closing, have reopened as #33

**Pull request closed without merging**
